[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[program:syslogd]
command=/sbin/syslogd -n
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:stunnel]
command=/usr/bin/stunnel
priority=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:tlsrpt-collectd]
command=/opt/tlsrpt-venv/bin/tlsrpt-collectd --config_file /etc/tlsrpt/collectd.cfg
priority=3
user=tlsrpt
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:postfix]
command=/usr/sbin/postfix start-fg
priority=4
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
